package com.yunos.killproject.dao;

import com.yunos.killproject.dataobject.CarModuleDo;

import java.util.List;

public interface CarModuleDoMapper {

    /**
     * 根据车型获取车型的详细信息
     *
     * @param carId 车型id
     * @return CarModuleModel
     */
    List<CarModuleDo> getCarDetailById(Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module
     *
     * @mbg.generated Sat Mar 30 11:50:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module
     *
     * @mbg.generated Sat Mar 30 11:50:42 CST 2019
     */
    int insert(CarModuleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module
     *
     * @mbg.generated Sat Mar 30 11:50:42 CST 2019
     */
    int insertSelective(CarModuleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module
     *
     * @mbg.generated Sat Mar 30 11:50:42 CST 2019
     */
    CarModuleDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module
     *
     * @mbg.generated Sat Mar 30 11:50:42 CST 2019
     */
    int updateByPrimaryKeySelective(CarModuleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module
     *
     * @mbg.generated Sat Mar 30 11:50:42 CST 2019
     */
    int updateByPrimaryKey(CarModuleDo record);
}