package com.yunos.killproject.dao;

import com.yunos.killproject.dataobject.CarModuleConfigDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarModuleConfigDoMapper {

    /**
     * 获取模块的详情配置信息
     *
     * @param carId
     * @param moduleId
     * @return
     */
    List<CarModuleConfigDo> getModuleConfig(@Param("carId") Integer carId, @Param("moduleId") Integer moduleId);

    /**
     * 根据车型id获取所有详情信息
     *
     * @param carId
     * @param carId
     * @return
     */
    List<CarModuleConfigDo> getModuleConfigByCarId(@Param("carId") Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module_config
     *
     * @mbg.generated Sat Mar 30 16:15:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module_config
     *
     * @mbg.generated Sat Mar 30 16:15:23 CST 2019
     */
    int insert(CarModuleConfigDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module_config
     *
     * @mbg.generated Sat Mar 30 16:15:23 CST 2019
     */
    int insertSelective(CarModuleConfigDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module_config
     *
     * @mbg.generated Sat Mar 30 16:15:23 CST 2019
     */
    CarModuleConfigDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module_config
     *
     * @mbg.generated Sat Mar 30 16:15:23 CST 2019
     */
    int updateByPrimaryKeySelective(CarModuleConfigDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_module_config
     *
     * @mbg.generated Sat Mar 30 16:15:23 CST 2019
     */
    int updateByPrimaryKey(CarModuleConfigDo record);
}