package com.yunos.killproject.dao;

import com.yunos.killproject.dataobject.PromoDo;

public interface PromoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Sat Mar 16 16:13:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Sat Mar 16 16:13:24 CST 2019
     */
    int insert(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Sat Mar 16 16:13:24 CST 2019
     */
    int insertSelective(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Sat Mar 16 16:13:24 CST 2019
     */
    PromoDo selectByPrimaryKey(Integer id);

    /**
     * 通过id 获取秒杀商品信息
     *
     * @param id
     * @return
     */
    PromoDo selectByItemId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Sat Mar 16 16:13:24 CST 2019
     */
    int updateByPrimaryKeySelective(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Sat Mar 16 16:13:24 CST 2019
     */
    int updateByPrimaryKey(PromoDo record);
}